apiVersion: v1
kind: Pod
metadata:
  name: hello-world
  namespace: default
  labels:
    app: hello
    propagate: "true"
spec:
  containers:
  - name: hello-container
    image: busybox
    command: ['sh', '-c', 'echo "Hello from Kubernetes!" && sleep 3600']
  restartPolicy: Always
