{
 "title": "K8S Control Plane",
 "description": "Metrics for API Server, Controller and Scheduler.",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "panels": [
  { "title": "API Server Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "API Server RPS",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(apiserver_request_total[5m]))",
     "legendFormat": "{{verb}}"
    }
   ]
  },
  {
   "title": "Current Inflight Requests",
   "type": "graph",
   "gridPos": { "h": 7, "w": 5, "x": 3, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(apiserver_current_inflight_requests) by (request_kind)",
     "legendFormat": "{{request_kind}}"
    }
   ]
  },
  {
   "title": "Latency - p99",
   "type": "graph",
   "gridPos": { "h": 7, "w": 5, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(apiserver_request_duration_seconds_bucket{verb!~\"WATCH|CONNECT\"}[5m])) by (le))"
    }
   ]
  },
  {
   "title": "API Server Response Duration (Seconds)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 5, "x": 13, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(apiserver_request_duration_seconds_sum{verb!~\"WATCH|CONNECT\"}[5m]))",
     "legendFormat": "seconds"
    }
   ]
  },
  {
   "title": "API Server Errors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 5, "x": 18, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(apiserver_request_total{code=~\"^(?:4..)$|^(?:5..)$\"}[5m])) by (code)>0",
     "legendFormat": "{{code}}"
    }
   ]
  },
  { "title": "Kube Controller Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Has Leader?",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 9 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(leader_election_master_status{name=\"kube-controller-manager\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Controller Manager Queue Depth",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 4, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(workqueue_depth{name=\"volumes\"}) ",
     "legendFormat": "volumes"
    },
    {
     "expr": "sum(workqueue_depth{name=\"deployment\"}) ",
     "legendFormat": "deployment"
    },
    {
     "expr": "sum(workqueue_depth{name=\"replicaset\"}) ",
     "legendFormat": "replicaset"
    },
    {
     "expr": "sum(workqueue_depth{name=\"service\"}) ",
     "legendFormat": "service"
    },
    {
     "expr": "sum(workqueue_depth{name=\"serviceaccount\"}) ",
     "legendFormat": "serviceaccount"
    },
    {
     "expr": "sum(workqueue_depth{name=\"endpoint\"}) ",
     "legendFormat": "endpoint"
    },
    {
     "expr": "sum(workqueue_depth{name=\"daemonset\"}) ",
     "legendFormat": "daemonset"
    },
    {
     "expr": "sum(workqueue_depth{name=\"statefulset\"}) ",
     "legendFormat": "statefulset"
    },
    {
     "expr": "sum(workqueue_depth{name=\"horizontalpodautoscaler\"})",
     "legendFormat": "horizontalpodautoscaler"
    }
   ]
  },
  {
   "title": "Controller Manager Adds",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 13, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(workqueue_adds_total{name=\"volumes\"}[5m])",
     "legendFormat": "volumes"
    },
    {
     "expr": "rate(workqueue_adds_total{name=\"deployment\"}[5m])",
     "legendFormat": "deployment"
    },
    {
     "expr": "rate(workqueue_adds_total{name=\"replicaset\"}[5m])",
     "legendFormat": "replicaset"
    },
    {
     "expr": "rate(workqueue_adds_total{name=\"service\"}[5m])",
     "legendFormat": "service"
    },
    {
     "expr": "rate(workqueue_adds_total{name=\"endpoint\"}[5m])",
     "legendFormat": "endpoints"
    },
    {
     "expr": "rate(workqueue_adds_total{name=\"daemonset\"}[5m])",
     "legendFormat": "daemonsets"
    },
    {
     "expr": "rate(workqueue_adds_total{name=\"statefulset\"}[5m])",
     "legendFormat": "statefulsets"
    },
    {
     "expr": "rate(workqueue_adds_total{name=\"horizontalpodautoscaler\"}[5m])",
     "legendFormat": "horizontalpodautoscaler"
    }
   ]
  },
  { "title": "Kube Scheduler Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Has Leader?",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 16 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(leader_election_master_status{name=\"kube-scheduler\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Scheduler Attempts",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 4, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(scheduler_schedule_attempts_total[1m])) by (result)",
     "legendFormat": "{{result}}"
    }
   ]
  },
  {
   "title": "Scheduler Duration",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 13, "y": 16 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(scheduler_scheduling_attempt_duration_seconds_bucket[5m])) by (le))",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "API Server Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "API Server Success",
     "type": "graph",
     "gridPos": { "h": 7, "w": 7, "x": 0, "y": 23 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(apiserver_request_total{code!~\"^(?:4..)$|^(?:5..)$\"}[5m])) by (code)>0",
       "legendFormat": "{{code}}"
      }
     ]
    },
    {
     "title": "API Server Requests (by Verb)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 7, "y": 23 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(apiserver_request_total[5m])) by (verb)",
       "legendFormat": "{{verb}}"
      }
     ]
    },
    {
     "title": "API Requests (by Resource)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 15, "y": 23 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(apiserver_request_total[5m])) by (resource)",
       "legendFormat": "{{resource}}"
      }
     ]
    },
    {
     "title": "API Requests by client (non-kube-*)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 23, "x": 0, "y": 30 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(apiserver_request_total{user_agent!~\"kubelet.*|kube-scheduler.*|kube-controller.*|kube-apiserver.*|kube-proxy.*\"}[5m])) by (user_agent)>0",
       "legendFormat": "{{user_agent}}"
      }
     ]
    },
    {
     "title": "API Requests by client (kube-*)",
     "type": "graph",
     "gridPos": { "h": 6, "w": 23, "x": 0, "y": 37 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(apiserver_request_total{user_agent=~\"kubelet.*|kube-scheduler.*|kube-controller.*|kube-apiserver.*|kube-proxy.*\"}[5m])) by (user_agent)>0",
       "legendFormat": "{{user_agent}}"
      }
     ]
    },
    {
     "title": "API Server Requests by server",
     "type": "graph",
     "gridPos": { "h": 8, "w": 7, "x": 0, "y": 43 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(apiserver_request_total[5m])) by (instance)>0",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Latency p90 by resource",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 7, "y": 43 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.90, sum(rate(apiserver_request_duration_seconds_bucket{verb!~\"WATCH|CONNECT\"}[5m])) by (le, resource))",
       "legendFormat": "{{resource}}"
      }
     ]
    },
    {
     "title": "API Server Response Duration - CONNECT",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 15, "y": 43 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum(rate(apiserver_request_duration_seconds_sum{verb=~\"CONNECT\"}[5m])) by (resource)/sum(rate(apiserver_request_duration_seconds_count{verb=~\"CONNECT\"}[5m])) by (resource)>0",
       "legendFormat": "{{resource}}"
      }
     ]
    }
   ]
  }
 ]
}